<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admins-MacBook-Pro.local" ignored="0" name="Registration" tests="8" failures="1" timestamp="2020-03-14T16:59:11 IST" time="105.987" errors="0">
  <testcase name="open_RegistrationPage" time="4.152" classname="com.shine.tests.Test_Registration"/>
  <testcase name="verify_open_registration_page_collect_view" time="0.223" classname="com.shine.tests.Test_Registration"/>
  <testcase name="registrationStep1" time="1.264" classname="com.shine.tests.Test_Registration"/>
  <testcase name="verify_email_already_registered_alert" time="9.092" classname="com.shine.tests.Test_Registration">
    <failure type="java.lang.AssertionError" message="Email id already exists: By.cssSelector: .error_message expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Email id already exists: By.cssSelector: .error_message expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.shine.tests.Test_Registration.verify_email_already_registered_alert(Test_Registration.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_email_already_registered_alert -->
  <testcase name="verify_already_registered_alert_login_link" time="0.0" classname="com.shine.tests.Test_Registration">
    <skipped/>
  </testcase> <!-- verify_already_registered_alert_login_link -->
  <testcase name="ChangePassword" time="0.004" classname="com.shine.tests.Test_Registration"/>
  <testcase name="registrationStep2" time="86.1" classname="com.shine.tests.Test_Registration"/>
  <testcase name="verify_registration_page2_collect_view" time="0.694" classname="com.shine.tests.Test_Registration"/>
</testsuite> <!-- Registration -->
